CREATE DATABASE loja_r7 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE loja_r7;

CREATE TABLE pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    itens TEXT NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
